table Cancelacion
	lineageTag: 58d65995-45e4-4158-acbd-1b79e92df66b

	measure 'Total de Ordenes' = COUNT(Cancelacion[ID de la encuesta]) + COUNT(Ventas[ID de la encuesta])
		formatString: 0
		lineageTag: 27a53a89-972e-4c23-bf52-d4a3e3e4a1fd

	column 'ID de la encuesta'
		dataType: int64
		formatString: 0
		lineageTag: 602d05db-9baf-4edb-97d1-1426e62e138f
		summarizeBy: none
		sourceColumn: ID de la encuesta

		annotation SummarizationSetBy = Automatic

	column 'Rótulo de la encuesta'
		dataType: string
		lineageTag: e22dd8a3-3b5e-48b2-a6ad-5a25d7248c1b
		summarizeBy: none
		sourceColumn: Rótulo de la encuesta

		annotation SummarizationSetBy = Automatic

	column Red
		dataType: string
		lineageTag: 8afb04b5-3f95-40eb-992e-fa8b1d98597f
		summarizeBy: none
		sourceColumn: Red

		annotation SummarizationSetBy = Automatic

	column Cadena
		dataType: string
		lineageTag: 9abe2f90-ec32-4e8a-9388-37169d0e803c
		summarizeBy: none
		sourceColumn: Cadena

		annotation SummarizationSetBy = Automatic

	column PDV
		dataType: string
		lineageTag: 1a9015ff-6bd0-4300-bb9c-55afe0689eca
		summarizeBy: none
		sourceColumn: PDV

		annotation SummarizationSetBy = Automatic

	column 'División territorial'
		dataType: string
		lineageTag: f4d9a5dd-4e1e-4f48-93b8-baeb7f8a5c6c
		summarizeBy: none
		sourceColumn: División territorial

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: 24f45ce6-73d3-4db7-b754-fc1dc28fdbe1
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: a9c140fd-d05f-46cb-b811-270776661b4d
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: d42e6ef2-68c0-4669-a120-e7f9b6bf80b3
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Empleado
		dataType: string
		lineageTag: f56367be-1f26-4191-bd56-b38b51303922
		summarizeBy: none
		sourceColumn: Empleado

		annotation SummarizationSetBy = Automatic

	column 'ID Pedido'
		dataType: string
		lineageTag: fc796bfc-c558-422c-9cd2-9e0e9a2f8e8f
		summarizeBy: none
		sourceColumn: ID Pedido

		annotation SummarizationSetBy = Automatic

	column 'Motivo de cancelación'
		dataType: string
		lineageTag: b9ec0874-7fdb-423d-b16c-805159663a28
		summarizeBy: none
		sourceColumn: Motivo de cancelación

		annotation SummarizationSetBy = Automatic

	column '¿Cuál es el precio que está registrado en la sucursal?'
		dataType: string
		lineageTag: eb830eb7-8de5-4e99-824c-214c0eb76553
		summarizeBy: none
		sourceColumn: ¿Cuál es el precio que está registrado en la sucursal?

		annotation SummarizationSetBy = Automatic

	column '¿Cuál es el precio registrado en la aplicación?'
		dataType: string
		lineageTag: ee82e2eb-f341-47a1-aaae-4338ef03a6ec
		summarizeBy: none
		sourceColumn: ¿Cuál es el precio registrado en la aplicación?

		annotation SummarizationSetBy = Automatic

	column '¿Qué promoción tienen en la sucursal?'
		dataType: string
		lineageTag: aef1f767-c498-4d43-8b39-5c41f935d92a
		summarizeBy: none
		sourceColumn: ¿Qué promoción tienen en la sucursal?

		annotation SummarizationSetBy = Automatic

	column '¿Cuál es la promoción que tienen en la aplicación?'
		dataType: string
		lineageTag: 2d93ab88-e9a7-461d-ad67-1184eb1dba96
		summarizeBy: none
		sourceColumn: ¿Cuál es la promoción que tienen en la aplicación?

		annotation SummarizationSetBy = Automatic

	column 'Detalles de cancelación'
		dataType: string
		lineageTag: 8b9193d6-42b5-40a7-849b-61ac9d4333e6
		summarizeBy: none
		sourceColumn: Detalles de cancelación

		annotation SummarizationSetBy = Automatic

	column Llave
		dataType: string
		lineageTag: cd57ac75-19cc-45f6-a900-4c30108eb48d
		summarizeBy: none
		sourceColumn: Llave

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(6)'
		dataType: string
		lineageTag: f52ee10e-3d22-42e4-a95f-5fba08b55f5c
		summarizeBy: none
		sourceColumn: Nombre del Producto(6)

		annotation SummarizationSetBy = Automatic

	column 'Cantidad de Productos Donados'
		dataType: string
		lineageTag: 94083424-6916-4fc5-847e-155e38ca60f7
		summarizeBy: none
		sourceColumn: Cantidad de Productos Donados

		annotation SummarizationSetBy = Automatic

	column 'Nombre de la persona que recibe la donación'
		dataType: string
		lineageTag: a6571440-94ab-4f2f-a0de-0b9fc81d618c
		summarizeBy: none
		sourceColumn: Nombre de la persona que recibe la donación

		annotation SummarizationSetBy = Automatic

	column 'Numero de contacto de quien recibe la donación'
		dataType: string
		lineageTag: b3f3c912-2561-4d42-ba5e-af30ca1a10e4
		summarizeBy: none
		sourceColumn: Numero de contacto de quien recibe la donación

		annotation SummarizationSetBy = Automatic

	column 'Motivo de la cancelación por repartidor'
		dataType: string
		lineageTag: f4561776-5b6b-4294-bf27-311ec7eea732
		summarizeBy: none
		sourceColumn: Motivo de la cancelación por repartidor

		annotation SummarizationSetBy = Automatic

	column 'Cantidad de Producto agotado'
		dataType: string
		lineageTag: a32c2bf5-72b1-488e-acdc-08a1b3f3aab7
		summarizeBy: none
		sourceColumn: Cantidad de Producto agotado

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados'
		dataType: string
		lineageTag: 6d89f7ed-618b-4f7c-87d8-11dc72d8b03d
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto'
		dataType: string
		lineageTag: 78c8bf32-9665-48b2-a0b7-763ea3b66061
		summarizeBy: none
		sourceColumn: Nombre del Producto

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)'
		dataType: string
		lineageTag: d5704124-c17a-49b2-862c-c6656300de23
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados(2)'
		dataType: string
		lineageTag: a35444ae-caf5-4317-836c-5d741c5289e0
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados(2)

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(2)'
		dataType: string
		lineageTag: 1b3b489b-329e-4293-9436-ff54209073a0
		summarizeBy: none
		sourceColumn: Nombre del Producto(2)

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)(2)'
		dataType: string
		lineageTag: be197499-248b-4334-81a4-11c4b4a572a8
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)(2)

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados(3)'
		dataType: string
		lineageTag: fba56947-7cb0-4224-a77b-843650d43fa8
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados(3)

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(3)'
		dataType: string
		lineageTag: 4f7c9dc4-a5a3-4f52-a083-efcd1470a08c
		summarizeBy: none
		sourceColumn: Nombre del Producto(3)

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)(3)'
		dataType: string
		lineageTag: 61b37c0d-12bc-4f7f-a8da-36a4ffe35fb0
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)(3)

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados(4)'
		dataType: string
		lineageTag: d886becc-971b-49cb-87e1-def5215541f7
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados(4)

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(4)'
		dataType: string
		lineageTag: 080e8b0f-c561-4d67-b33d-f70de9c2f91a
		summarizeBy: none
		sourceColumn: Nombre del Producto(4)

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)(4)'
		dataType: string
		lineageTag: a395dab2-00eb-4235-be61-488d3f189759
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)(4)

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados(5)'
		dataType: string
		lineageTag: 651a3a62-012a-4efb-9353-0871a2a77aa7
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados(5)

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(5)'
		dataType: string
		lineageTag: ea6d001a-d36a-413a-840a-1d6eb27635e7
		summarizeBy: none
		sourceColumn: Nombre del Producto(5)

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)(5)'
		dataType: string
		lineageTag: 677d76d8-6beb-45f3-a80b-141faf61cb74
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)(5)

		annotation SummarizationSetBy = Automatic

	column '¿Valido si el Producto esta en Bodega?'
		dataType: string
		lineageTag: f865b5b2-ae52-40db-a70b-6c1a20aaba8f
		summarizeBy: none
		sourceColumn: ¿Valido si el Producto esta en Bodega?

		annotation SummarizationSetBy = Automatic

	column '¿Por que no valido la existencia del Producto en Bodega?'
		dataType: string
		lineageTag: 0ac9a745-1364-4dae-b6d5-a39f216cb0b6
		summarizeBy: none
		sourceColumn: ¿Por que no valido la existencia del Producto en Bodega?

		annotation SummarizationSetBy = Automatic

	column 'Perfil de acceso'
		dataType: string
		lineageTag: 4f881514-d441-4ebb-9aed-98a94828e37e
		summarizeBy: none
		sourceColumn: Perfil de acceso

		annotation SummarizationSetBy = Automatic

	column 'Motivo de Cancelación del Cliente'
		dataType: string
		lineageTag: 35a399f6-c534-4250-991a-4cc930d3a460
		summarizeBy: none
		sourceColumn: Motivo de Cancelación del Cliente

		annotation SummarizationSetBy = Automatic

	partition Cancelacion = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\adrian.arriaga\OneDrive - Adecco\Documents\Adrian\Didi\Dashboard_Ventas_Cancelaciones\CANCELACION.xlsx"), null, true),
				    report_Sheet = Origen{[Item="report",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos1" = Table.PromoteHeaders(report_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Encabezados promovidos1",{{"ID de la encuesta", Int64.Type}, {"Rótulo de la encuesta", type text}, {"Red", type text}, {"Cadena", type text}, {"PDV", type text}, {"División territorial", type text}, {"Ciudad", type text}, {"Regional", type text}, {"Fecha y hora de la encuesta", type datetime}, {"Empleado", type text}, {"ID Pedido", type text}, {"Motivo de cancelación", type text}, {"¿Cuál es el precio que está registrado en la sucursal?", type any}, {"¿Cuál es el precio registrado en la aplicación?", type any}, {"¿Qué promoción tienen en la sucursal?", type any}, {"¿Cuál es la promoción que tienen en la aplicación?", type any}, {"Detalles de cancelación", type text}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo cambiado4",{{"ID de la encuesta", Int64.Type}, {"Rótulo de la encuesta", type text}, {"Red", type text}, {"Cadena", type text}, {"PDV", type text}, {"División territorial", type text}, {"Ciudad", type text}, {"Regional", type text}, {"Fecha y hora de la encuesta", type datetime}, {"Empleado", type text}, {"ID Pedido", type text}, {"Motivo de cancelación", type text}, {"¿Cuál es el precio que está registrado en la sucursal?", type any}, {"¿Cuál es el precio registrado en la aplicación?", type any}, {"¿Qué promoción tienen en la sucursal?", type any}, {"¿Cuál es la promoción que tienen en la aplicación?", type any}, {"Detalles de cancelación", type text}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado",null,"Bogotá D.C.",Replacer.ReplaceValue,{"División territorial"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado",null,"Bogotá",Replacer.ReplaceValue,{"Ciudad"}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Valor reemplazado1",{{"Fecha y hora de la encuesta", "Fecha"}}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas con nombre cambiado",{{"Fecha", type date}, {"Motivo de la cancelación por repartidor", type text}}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Tipo cambiado1",{{"Motivo de la cancelación por repartidor", Text.Proper, type text}, {"Detalles de cancelación", Text.Proper, type text}})
				in
				    #"Poner En Mayúsculas Cada Palabra"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

