table Cancelacion+Ventas
	lineageTag: 8df5e589-56db-4eec-8042-a3a61f25f7ab

	measure 'Índice de Cancelación (%)' = ```
			
			DIVIDE(
			    COUNTROWS(FILTER('Cancelacion+Ventas', 'Cancelacion+Ventas'[Estado] = "Cancelado")),
			    COUNTROWS('Cancelacion+Ventas'),
			    0
			)
			
			```
		formatString: 0\ %;-0\ %;0\ %
		lineageTag: 45bb7a75-4eee-489e-aae6-7d1bcf4dc404

	measure Cadena2 = ```
			
			    COUNTROWS(FILTER('Cancelacion+Ventas', 'Cancelacion+Ventas'[Estado] = "Cancelado"))
			```
		formatString: 0
		lineageTag: 70e30603-d342-4dab-9436-66145acd0ae4

	measure CantidadPorTipoPDV = ```
			
			CALCULATE(
			    COUNTROWS('Cancelacion+Ventas'),
			    ALLEXCEPT('Pdv DiDi', 'Pdv DiDi'[Tipo de PDV])
			)
			
			```
		formatString: 0
		lineageTag: f97a5f1e-fe55-460b-8cb6-19700b6a51f1

	column 'ID de la encuesta'
		dataType: string
		lineageTag: 4a8bcc74-93ab-4a01-8595-e8b829c1dbb7
		summarizeBy: none
		sourceColumn: ID de la encuesta

		annotation SummarizationSetBy = Automatic

	column 'Rótulo de la encuesta'
		dataType: string
		lineageTag: 2d4905ff-d39f-49ba-8de1-800e28f39322
		summarizeBy: none
		sourceColumn: Rótulo de la encuesta

		annotation SummarizationSetBy = Automatic

	column Red
		dataType: string
		lineageTag: ecf8d259-70ad-4dfc-97e4-7197b1ffe6d6
		summarizeBy: none
		sourceColumn: Red

		annotation SummarizationSetBy = Automatic

	column Cadena
		dataType: string
		lineageTag: 5ee23a44-d3c2-49ce-a3b5-20fa7ffdad8c
		summarizeBy: none
		sourceColumn: Cadena

		annotation SummarizationSetBy = Automatic

	column PDV
		dataType: string
		lineageTag: 16687434-0768-4693-8d20-4b8255575460
		summarizeBy: none
		sourceColumn: PDV

		annotation SummarizationSetBy = Automatic

	column 'División territorial'
		dataType: string
		lineageTag: 39ac679d-be42-4327-9350-a524f55be4e2
		summarizeBy: none
		sourceColumn: División territorial

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: 994496ad-d621-4910-ac25-0d66e7a94829
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 451b6534-09ef-4f05-b30c-624a77c50be6
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Fecha y hora de la encuesta'
		dataType: dateTime
		formatString: d/mm/yyyy
		lineageTag: 94615590-3839-4fa7-8e49-c5850e21c1ec
		summarizeBy: none
		sourceColumn: Fecha y hora de la encuesta

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column Empleado
		dataType: string
		lineageTag: e169b5b6-18a7-4ad6-b10a-dcb6f9209601
		summarizeBy: none
		sourceColumn: Empleado

		annotation SummarizationSetBy = Automatic

	column 'ID Pedido'
		dataType: string
		lineageTag: d343be2a-cb79-4f27-9c2e-5fb94d980546
		summarizeBy: none
		sourceColumn: ID Pedido

		annotation SummarizationSetBy = Automatic

	column 'Motivo de cancelación'
		dataType: string
		lineageTag: 599aef5b-9ba9-4398-a670-26c82d039107
		summarizeBy: none
		sourceColumn: Motivo de cancelación

		annotation SummarizationSetBy = Automatic

	column '¿Cuál es el precio que está registrado en la sucursal?'
		dataType: string
		lineageTag: 081adc64-9ebe-40e7-bfb5-8e6622d1b0cc
		summarizeBy: none
		sourceColumn: ¿Cuál es el precio que está registrado en la sucursal?

		annotation SummarizationSetBy = Automatic

	column '¿Cuál es el precio registrado en la aplicación?'
		dataType: string
		lineageTag: c6762cce-ed3b-4f86-a695-be13fd40b5aa
		summarizeBy: none
		sourceColumn: ¿Cuál es el precio registrado en la aplicación?

		annotation SummarizationSetBy = Automatic

	column '¿Qué promoción tienen en la sucursal?'
		dataType: string
		lineageTag: 473053a7-95c4-4da9-aa50-b271eb32c6e5
		summarizeBy: none
		sourceColumn: ¿Qué promoción tienen en la sucursal?

		annotation SummarizationSetBy = Automatic

	column '¿Cuál es la promoción que tienen en la aplicación?'
		dataType: string
		lineageTag: f25de468-247a-4ee3-8409-c530c41981ff
		summarizeBy: none
		sourceColumn: ¿Cuál es la promoción que tienen en la aplicación?

		annotation SummarizationSetBy = Automatic

	column 'Detalles de cancelación'
		dataType: string
		lineageTag: 6644616e-2f1c-478b-8466-bd271cf1586a
		summarizeBy: none
		sourceColumn: Detalles de cancelación

		annotation SummarizationSetBy = Automatic

	column Estado = IF('Cancelacion+Ventas'[Motivo de cancelación]<> BLANK(),"cancelado","")
		lineageTag: 70b6a502-60ce-4543-b557-18f0c899bc7f
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column 'Cantidad de articulos'
		dataType: int64
		formatString: 0
		lineageTag: 7355bb3e-928e-44de-bb11-3c3d3ab24209
		summarizeBy: sum
		sourceColumn: Cantidad de articulos

		annotation SummarizationSetBy = Automatic

	column '¿A qué hora recibiste el pedido en la aplicación?'
		dataType: dateTime
		formatString: Long Time
		lineageTag: cd1051b9-fd77-49e0-b59e-afe3201f8982
		summarizeBy: none
		sourceColumn: ¿A qué hora recibiste el pedido en la aplicación?

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column '¿A qué hora fue registrado el pago?'
		dataType: dateTime
		formatString: Long Time
		lineageTag: fa270872-e2e0-4944-8cef-393d14cad886
		summarizeBy: none
		sourceColumn: ¿A qué hora fue registrado el pago?

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Empleado2
		dataType: string
		lineageTag: 5fc0d88c-c92c-4ac8-b2b1-c0da47901615
		summarizeBy: none
		sourceColumn: Empleado2

		annotation SummarizationSetBy = Automatic

	column PDV2
		dataType: string
		lineageTag: 1bfe64ed-5eaf-4d2c-bd66-8671e2a88f3f
		summarizeBy: none
		sourceColumn: PDV2

		annotation SummarizationSetBy = Automatic

	column 'Cantidad total de la Factura'
		dataType: int64
		formatString: 0
		lineageTag: 7d666e9f-639f-4c0e-b7f9-ec76a6dbb1a0
		summarizeBy: sum
		sourceColumn: Cantidad total de la Factura

		annotation SummarizationSetBy = Automatic

	column Llave
		dataType: string
		lineageTag: abe00f6c-ac49-4126-8f5f-4a8b99e3ec8e
		summarizeBy: none
		sourceColumn: Llave

		annotation SummarizationSetBy = Automatic

	column 'Pdv DiDi.Tipo de PDV'
		dataType: string
		lineageTag: a16e6f84-0fcc-45f0-aab8-8f2c1e54abb9
		summarizeBy: none
		sourceColumn: Pdv DiDi.Tipo de PDV

		annotation SummarizationSetBy = Automatic

	column Llave3
		dataType: string
		lineageTag: 9e639274-6935-48ea-b314-c30316d2558e
		summarizeBy: none
		sourceColumn: Llave3

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(6)'
		dataType: string
		lineageTag: ff0bda0f-09f5-4541-b681-31e1dbae3e36
		summarizeBy: none
		sourceColumn: Nombre del Producto(6)

		annotation SummarizationSetBy = Automatic

	column 'Cantidad de Productos Donados'
		dataType: string
		lineageTag: 8767bfee-2c0d-4045-86ef-877d5fda7fb1
		summarizeBy: none
		sourceColumn: Cantidad de Productos Donados

		annotation SummarizationSetBy = Automatic

	column 'Nombre de la persona que recibe la donación'
		dataType: string
		lineageTag: 252f9f8a-98e7-4d8e-94d7-1a58fbe6e5a4
		summarizeBy: none
		sourceColumn: Nombre de la persona que recibe la donación

		annotation SummarizationSetBy = Automatic

	column 'Numero de contacto de quien recibe la donación'
		dataType: string
		lineageTag: f522ce30-95ca-4dd4-90ee-e02248a6c4ea
		summarizeBy: none
		sourceColumn: Numero de contacto de quien recibe la donación

		annotation SummarizationSetBy = Automatic

	column 'Motivo de la cancelación por repartidor'
		dataType: string
		lineageTag: a27cb043-467b-400b-b4ab-676c25484b45
		summarizeBy: none
		sourceColumn: Motivo de la cancelación por repartidor

		annotation SummarizationSetBy = Automatic

	column 'Cantidad de Producto agotado'
		dataType: string
		lineageTag: fa95e916-6d57-4200-a130-78c0d8a1a0ec
		summarizeBy: none
		sourceColumn: Cantidad de Producto agotado

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados'
		dataType: string
		lineageTag: 02fabdc5-f5ae-4156-8b78-5e7a7f51a4a1
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto'
		dataType: string
		lineageTag: b775ae66-e5d5-40ac-a4bf-9c733a56031b
		summarizeBy: none
		sourceColumn: Nombre del Producto

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)'
		dataType: string
		lineageTag: 84856aff-9191-4db4-be8b-abf17337149e
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados(2)'
		dataType: string
		lineageTag: a6ca619e-4ccb-454a-a495-d464d251f8f1
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados(2)

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(2)'
		dataType: string
		lineageTag: d9b9c9f1-14bf-4c6d-8c70-4acf78ca7909
		summarizeBy: none
		sourceColumn: Nombre del Producto(2)

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)(2)'
		dataType: string
		lineageTag: 85127137-b9c4-4e5c-9db3-d22a2eb9c532
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)(2)

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados(3)'
		dataType: string
		lineageTag: c9a873eb-2157-4ef7-bdc7-455c42c292f1
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados(3)

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(3)'
		dataType: string
		lineageTag: 20a83a05-1fed-449b-8c6d-b5d36f768981
		summarizeBy: none
		sourceColumn: Nombre del Producto(3)

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)(3)'
		dataType: string
		lineageTag: 338e6cc5-c1d7-4d11-9b42-cef81842e243
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)(3)

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados(4)'
		dataType: string
		lineageTag: 389d4d1a-d1eb-461d-8ec2-773dcf3db91a
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados(4)

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(4)'
		dataType: string
		lineageTag: e86b2ea6-a196-4c1e-8a2e-05064ce6fc57
		summarizeBy: none
		sourceColumn: Nombre del Producto(4)

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)(4)'
		dataType: string
		lineageTag: 7e4040ec-080e-431a-9cee-61d53c43a628
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)(4)

		annotation SummarizationSetBy = Automatic

	column 'Categoría de los Productos Agotados(5)'
		dataType: string
		lineageTag: f7e71c2d-6e11-4b95-921a-e11cba1ea8e4
		summarizeBy: none
		sourceColumn: Categoría de los Productos Agotados(5)

		annotation SummarizationSetBy = Automatic

	column 'Nombre del Producto(5)'
		dataType: string
		lineageTag: cdefb44d-dcc7-4841-aed9-c5523666d02e
		summarizeBy: none
		sourceColumn: Nombre del Producto(5)

		annotation SummarizationSetBy = Automatic

	column 'Gramaje (Litros, Gramos, Kilos etc.)(5)'
		dataType: string
		lineageTag: 5691f3a0-a1ca-4bfd-9d9d-924af2727cd1
		summarizeBy: none
		sourceColumn: Gramaje (Litros, Gramos, Kilos etc.)(5)

		annotation SummarizationSetBy = Automatic

	column '¿Valido si el Producto esta en Bodega?'
		dataType: string
		lineageTag: 593728b5-020b-4f52-bb6f-8f9535aead22
		summarizeBy: none
		sourceColumn: ¿Valido si el Producto esta en Bodega?

		annotation SummarizationSetBy = Automatic

	column '¿Por que no valido la existencia del Producto en Bodega?'
		dataType: string
		lineageTag: ee502238-86cb-4ae5-93e6-9315130daf6f
		summarizeBy: none
		sourceColumn: ¿Por que no valido la existencia del Producto en Bodega?

		annotation SummarizationSetBy = Automatic

	column 'Perfil de acceso'
		dataType: string
		lineageTag: 825057e6-edb5-4f75-980a-48407406943a
		summarizeBy: none
		sourceColumn: Perfil de acceso

		annotation SummarizationSetBy = Automatic

	column 'Motivo de Cancelación del Cliente'
		dataType: string
		lineageTag: fe44713c-9629-4f6b-9ce8-83ba67701f91
		summarizeBy: none
		sourceColumn: Motivo de Cancelación del Cliente

		annotation SummarizationSetBy = Automatic

	column '¿Se solicito vehículo para la orden?'
		dataType: string
		lineageTag: f9a02b4e-2a78-476c-bac8-04928c6b6202
		summarizeBy: none
		sourceColumn: ¿Se solicito vehículo para la orden?

		annotation SummarizationSetBy = Automatic

	column 'Tipo de vehiculo'
		dataType: string
		lineageTag: db624371-f3fa-4674-85c6-33d5d17a1684
		summarizeBy: none
		sourceColumn: Tipo de vehiculo

		annotation SummarizationSetBy = Automatic

	column 'Costo del vehiculo'
		dataType: string
		lineageTag: 42fa1a08-e90e-4b9e-a407-8e47014e4098
		summarizeBy: none
		sourceColumn: Costo del vehiculo

		annotation SummarizationSetBy = Automatic

	hierarchy 'Motivo de cancelación Jerarquía'
		lineageTag: 784df384-0db3-4667-b9e4-5def70f3cad2

		level 'Motivo de cancelación'
			lineageTag: 94bacac7-f604-47ae-95d9-43f48c4888ef
			column: 'Motivo de cancelación'

		level 'Detalles de cancelación'
			lineageTag: c7c98b2a-61c1-4993-9478-37fcc6d4db68
			column: 'Detalles de cancelación'

	partition Cancelacion+Ventas = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\adrian.arriaga\OneDrive - Adecco\Documents\Adrian\Didi\Dashboard_Ventas_Cancelaciones\CANCELACION.xlsx"), null, true),
				    report_Sheet = Origen{[Item="report",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos1" = Table.PromoteHeaders(report_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado4" = Table.TransformColumnTypes(#"Encabezados promovidos1",{{"ID de la encuesta", Int64.Type}, {"Rótulo de la encuesta", type text}, {"Red", type text}, {"Cadena", type text}, {"PDV", type text}, {"División territorial", type text}, {"Ciudad", type text}, {"Regional", type text}, {"Fecha y hora de la encuesta", type datetime}, {"Empleado", type text}, {"ID Pedido", type text}, {"Motivo de cancelación", type text}, {"¿Cuál es el precio que está registrado en la sucursal?", type any}, {"¿Cuál es el precio registrado en la aplicación?", type any}, {"¿Qué promoción tienen en la sucursal?", type any}, {"¿Cuál es la promoción que tienen en la aplicación?", type any}, {"Detalles de cancelación", type text}}),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Tipo cambiado4",{{"ID de la encuesta", Int64.Type}, {"Rótulo de la encuesta", type text}, {"Red", type text}, {"Cadena", type text}, {"PDV", type text}, {"División territorial", type text}, {"Ciudad", type text}, {"Regional", type text}, {"Fecha y hora de la encuesta", type datetime}, {"Empleado", type text}, {"ID Pedido", type text}, {"Motivo de cancelación", type text}, {"¿Cuál es el precio que está registrado en la sucursal?", type any}, {"¿Cuál es el precio registrado en la aplicación?", type any}, {"¿Qué promoción tienen en la sucursal?", type any}, {"¿Cuál es la promoción que tienen en la aplicación?", type any}, {"Detalles de cancelación", type text}}),
				    #"Valor reemplazado" = Table.ReplaceValue(#"Tipo cambiado",null,"Bogotá D.C.",Replacer.ReplaceValue,{"División territorial"}),
				    #"Valor reemplazado1" = Table.ReplaceValue(#"Valor reemplazado",null,"Bogotá",Replacer.ReplaceValue,{"Ciudad"}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Valor reemplazado1",{{"Detalles de cancelación", Text.Proper, type text}}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Poner En Mayúsculas Cada Palabra",{{"Fecha y hora de la encuesta", type date}}),
				    #"Consulta anexada" = Table.Combine({#"Tipo cambiado1", Ventas}),
				    #"Personalizada agregada" = Table.AddColumn(#"Consulta anexada", "Empleado2", each if [Motivo de cancelación] = null then " " else [Empleado]),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Personalizada agregada",{{"Empleado2", type text}}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Tipo cambiado2", "PDV2", each if [Motivo de cancelación] = null then " " else [PDV]),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Personalizada agregada1",{{"PDV2", type text}, {"Fecha y hora de la encuesta", type date}}),
				    #"Poner En Mayúsculas Cada Palabra1" = Table.TransformColumns(#"Tipo cambiado3",{{"Motivo de cancelación", Text.Proper, type text}}),
				    #"Consultas combinadas" = Table.NestedJoin(#"Poner En Mayúsculas Cada Palabra1", {"PDV"}, #"Pdv DiDi", {"Nombre del PDV"}, "Pdv DiDi", JoinKind.LeftOuter),
				    #"Se expandió Pdv DiDi" = Table.ExpandTableColumn(#"Consultas combinadas", "Pdv DiDi", {"Tipo de PDV"}, {"Pdv DiDi.Tipo de PDV"}),
				    #"Tipo cambiado5" = Table.TransformColumnTypes(#"Se expandió Pdv DiDi",{{"ID de la encuesta", type text}}),
				    #"Personalizada agregada2" = Table.AddColumn(#"Tipo cambiado5", "Llave3", each [ID de la encuesta]&"-"&[PDV])
				in
				    #"Personalizada agregada2"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

