table Categorias
	lineageTag: 2027708b-4c77-4673-a928-cd36b9b76a31

	column 'ID de la encuesta'
		dataType: int64
		formatString: 0
		lineageTag: a1ba56c7-c827-48a7-a67a-c9003008aaf1
		summarizeBy: none
		sourceColumn: ID de la encuesta

		annotation SummarizationSetBy = Automatic

	column PDV
		dataType: string
		lineageTag: 6c59b0fb-9f62-4583-b1fe-bc96fbcc2ebb
		summarizeBy: none
		sourceColumn: PDV

		annotation SummarizationSetBy = Automatic

	column 'División territorial'
		dataType: string
		lineageTag: bfe7c01d-c295-4503-b681-1a1829aa5608
		summarizeBy: none
		sourceColumn: División territorial

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: eab3a39f-b012-4298-b707-20f6aeb6450d
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 5ef009b7-aa5b-4e60-ad50-252ba77bbd0a
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column 'Fecha y hora de la encuesta'
		dataType: dateTime
		formatString: General Date
		lineageTag: f3e1e246-aa80-4921-a692-eaee79d325ef
		summarizeBy: none
		sourceColumn: Fecha y hora de la encuesta

		variation Variación
			isDefault
			relationship: 8f73e5ef-dd28-4d97-9dff-5abfec70fe5c
			defaultHierarchy: LocalDateTable_d0162265-1e7b-427a-b299-c67e79976b42.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Empleado
		dataType: string
		lineageTag: b72fb367-7d0f-489c-817d-b9df10c8ab10
		summarizeBy: none
		sourceColumn: Empleado

		annotation SummarizationSetBy = Automatic

	column 'Perfil de acceso'
		dataType: string
		lineageTag: 30d13659-675e-4ecb-b60a-5e5587d1fb39
		summarizeBy: none
		sourceColumn: Perfil de acceso

		annotation SummarizationSetBy = Automatic

	column 'Motivo de cancelación'
		dataType: string
		lineageTag: e150b781-4867-4400-9625-ab7d50a3ae87
		summarizeBy: none
		sourceColumn: Motivo de cancelación

		annotation SummarizationSetBy = Automatic

	column 'Cantidad de Producto agotado'
		dataType: int64
		formatString: 0
		lineageTag: 4a90e153-07a7-4956-b3bc-4e9d386ef774
		summarizeBy: sum
		sourceColumn: Cantidad de Producto agotado

		annotation SummarizationSetBy = Automatic

	column Atributo
		dataType: string
		lineageTag: f1bbe721-a588-4572-b041-bb536ddd4b99
		summarizeBy: none
		sourceColumn: Atributo

		annotation SummarizationSetBy = Automatic

	column Categoria
		dataType: string
		lineageTag: cba12505-ea77-4c57-b7f3-050d3e927ebf
		summarizeBy: none
		sourceColumn: Categoria

		annotation SummarizationSetBy = Automatic

	column Nombre
		dataType: string
		lineageTag: 3a5c09d0-081a-4280-9722-a00475170453
		summarizeBy: none
		sourceColumn: Nombre

		annotation SummarizationSetBy = Automatic

	column Gramaje
		dataType: string
		lineageTag: a3e45d82-1206-4fbc-89d6-04b6ba92e98e
		summarizeBy: none
		sourceColumn: Gramaje

		annotation SummarizationSetBy = Automatic

	column '¿Valido si el Producto esta en Bodega?'
		dataType: string
		lineageTag: a7562429-a097-4650-9160-884314c640fb
		summarizeBy: none
		sourceColumn: ¿Valido si el Producto esta en Bodega?

		annotation SummarizationSetBy = Automatic

	column '¿Por que no valido la existencia del Producto en Bodega?'
		dataType: string
		lineageTag: fae5e69f-0ecc-4c17-8937-62e16f3c9274
		summarizeBy: none
		sourceColumn: ¿Por que no valido la existencia del Producto en Bodega?

		annotation SummarizationSetBy = Automatic

	column 'Detalles de cancelación'
		dataType: string
		lineageTag: d7ba32cf-f603-4fe5-842f-444b3ef78ad9
		summarizeBy: none
		sourceColumn: Detalles de cancelación

		annotation SummarizationSetBy = Automatic

	column Llave
		dataType: string
		lineageTag: ea0a1af8-4e83-4a11-a08d-0b0e731de9c6
		summarizeBy: none
		sourceColumn: Llave

		annotation SummarizationSetBy = Automatic

	column 'Motivo de Cancelación del Cliente'
		dataType: string
		lineageTag: 9757b6f3-dc81-4335-a3f0-ec101d5d76f0
		summarizeBy: none
		sourceColumn: Motivo de Cancelación del Cliente

		annotation SummarizationSetBy = Automatic

	partition Categorias = m
		mode: import
		queryGroup: 'Categorias de agotados'
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\adrian.arriaga\OneDrive - Adecco\Documents\Adrian\Didi\Dashboard_Ventas_Cancelaciones\CANCELACION.xlsx"), null, true),
				    CATEGORIA_Sheet = Origen{[Item="CATEGORIA",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(CATEGORIA_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID de la encuesta", Int64.Type}, {"PDV", type text}, {"División territorial", type text}, {"Ciudad", type text}, {"Regional", type text}, {"Fecha y hora de la encuesta", type datetime}, {"Empleado", type text}, {"Perfil de acceso", type text}, {"Motivo de cancelación", type text}, {"Cantidad de Producto agotado", Int64.Type}, {"Atributo", type text}, {"Categoria", type text}, {"Nombre", type text}, {"Gramaje", type text}, {"¿Valido si el Producto esta en Bodega?", type text}, {"¿Por que no valido la existencia del Producto en Bodega?", type text}, {"Detalles de cancelación", type text}, {"Llave", type text}}),
				    #"Poner En Mayúsculas Cada Palabra" = Table.TransformColumns(#"Tipo cambiado",{{"Empleado", Text.Proper, type text}})
				in
				    #"Poner En Mayúsculas Cada Palabra"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

