table 'Pdv DiDi'
	lineageTag: 56ae5201-7bd5-44c7-8df6-47b75b95f8bc

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 2a4c37ba-7bb6-4af8-b174-9056989ee54f
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Nombre del PDV'
		dataType: string
		lineageTag: e81d3d96-1b5b-4aea-b957-2ce2e21fb92b
		summarizeBy: none
		sourceColumn: Nombre del PDV

		annotation SummarizationSetBy = Automatic

	column 'Nombre de fantasía'
		dataType: string
		lineageTag: 93c01b15-f58c-4a0b-95e9-375afd466ff0
		summarizeBy: none
		sourceColumn: Nombre de fantasía

		annotation SummarizationSetBy = Automatic

	column 'Razón social'
		dataType: string
		lineageTag: e7a2a6c1-3005-4404-aca4-2341919a066d
		summarizeBy: none
		sourceColumn: Razón social

		annotation SummarizationSetBy = Automatic

	column Cadena
		dataType: string
		lineageTag: 933cec0c-d775-4db9-af1e-2423161582fa
		summarizeBy: none
		sourceColumn: Cadena

		annotation SummarizationSetBy = Automatic

	column Red
		dataType: string
		lineageTag: 90de7301-30b1-438f-aefd-70b658ec5f05
		summarizeBy: none
		sourceColumn: Red

		annotation SummarizationSetBy = Automatic

	column 'Tipo de PDV'
		dataType: string
		lineageTag: dcf4261f-2891-4666-a240-c51f1a4e5239
		summarizeBy: none
		sourceColumn: Tipo de PDV

		annotation SummarizationSetBy = Automatic

	column 'Perfil del PDV'
		dataType: string
		lineageTag: 030fc236-b1b6-4f6a-89f7-8545e9983a48
		summarizeBy: none
		sourceColumn: Perfil del PDV

		annotation SummarizationSetBy = Automatic

	column 'Canal del PDV'
		dataType: string
		lineageTag: d63b6678-b5b8-46cd-9eab-21b2d99d5d7c
		summarizeBy: none
		sourceColumn: Canal del PDV

		annotation SummarizationSetBy = Automatic

	column 'Núm. del PDV'
		dataType: string
		lineageTag: 69c8d2c7-9619-4df5-a0ff-0995c6236591
		summarizeBy: none
		sourceColumn: Núm. del PDV

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 512aca70-6e82-4fd1-8bc8-caf31bc45e73
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Macrorregional
		dataType: string
		lineageTag: 074f9623-a928-4678-af46-3895284ff42f
		summarizeBy: none
		sourceColumn: Macrorregional

		annotation SummarizationSetBy = Automatic

	column 'Código del PDV'
		dataType: string
		lineageTag: 7db76cfe-f706-4fbe-862e-29efe43fdca8
		summarizeBy: none
		sourceColumn: Código del PDV

		annotation SummarizationSetBy = Automatic

	column 'Cantidad de cajas'
		dataType: string
		lineageTag: 5f878777-5008-47ee-bc1d-6127d2314aab
		summarizeBy: none
		sourceColumn: Cantidad de cajas

		annotation SummarizationSetBy = Automatic

	column Gerente
		dataType: string
		lineageTag: aef6c101-4f46-4414-9b42-d2919be43e01
		summarizeBy: none
		sourceColumn: Gerente

		annotation SummarizationSetBy = Automatic

	column 'Cumpleaños del gerente'
		dataType: string
		lineageTag: b7d766c4-4da6-417f-84c3-dccedd8a68d4
		summarizeBy: none
		sourceColumn: Cumpleaños del gerente

		annotation SummarizationSetBy = Automatic

	column 'Núm. de Identificación Empresarial'
		dataType: string
		lineageTag: 6d151a4e-ff34-442e-9a1c-195f8cfe7f04
		summarizeBy: none
		sourceColumn: Núm. de Identificación Empresarial

		annotation SummarizationSetBy = Automatic

	column Teléfono
		dataType: string
		lineageTag: 0f6f8ec6-3ad3-4112-befc-1933ca98c18d
		summarizeBy: none
		sourceColumn: Teléfono

		annotation SummarizationSetBy = Automatic

	column FAX
		dataType: string
		lineageTag: 20a96fe9-f8ce-40c4-b3a9-40fd588da7ca
		summarizeBy: none
		sourceColumn: FAX

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: fdb993c9-240b-47f9-a0b0-492b60cc7a18
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column 'División territorial'
		dataType: string
		lineageTag: f3d69467-e33a-4294-9f35-1767e994de54
		summarizeBy: none
		sourceColumn: División territorial

		annotation SummarizationSetBy = Automatic

	column Dirección
		dataType: string
		lineageTag: 33cf07ec-1b17-487a-888c-5da283063f19
		summarizeBy: none
		sourceColumn: Dirección

		annotation SummarizationSetBy = Automatic

	column Número
		dataType: string
		lineageTag: 0222b0da-d306-48cc-b912-031f7848dc0a
		summarizeBy: none
		sourceColumn: Número

		annotation SummarizationSetBy = Automatic

	column Complemento
		dataType: string
		lineageTag: fd430571-621c-4331-98f3-97ea13635045
		summarizeBy: none
		sourceColumn: Complemento

		annotation SummarizationSetBy = Automatic

	column Barrio
		dataType: string
		lineageTag: ba5a68c3-e7a0-4cf2-811f-912f2647ae53
		summarizeBy: none
		sourceColumn: Barrio

		annotation SummarizationSetBy = Automatic

	column 'Código postal'
		dataType: string
		lineageTag: eb9c3429-9cbb-400a-80a8-93116ab4397b
		summarizeBy: none
		sourceColumn: Código postal

		annotation SummarizationSetBy = Automatic

	column Latitud
		dataType: string
		lineageTag: bfdc67f3-c365-4783-985c-fcaaa877e711
		summarizeBy: none
		sourceColumn: Latitud

		annotation SummarizationSetBy = Automatic

	column Longitud
		dataType: string
		lineageTag: 4feccc29-f37f-41b0-a8ff-a9d6023f566b
		summarizeBy: none
		sourceColumn: Longitud

		annotation SummarizationSetBy = Automatic

	column 'Centro comercial'
		dataType: string
		lineageTag: 1f09081c-da7b-47dd-ae6b-f98a1cad4a50
		summarizeBy: none
		sourceColumn: Centro comercial

		annotation SummarizationSetBy = Automatic

	column Facturación
		dataType: string
		lineageTag: 90e078af-ad8e-49e4-b0d8-5df931526436
		summarizeBy: none
		sourceColumn: Facturación

		annotation SummarizationSetBy = Automatic

	column Volumen
		dataType: string
		lineageTag: 0dd1a9f5-4f1f-4ef0-a912-3da3ea6072e3
		summarizeBy: none
		sourceColumn: Volumen

		annotation SummarizationSetBy = Automatic

	column 'Nombre del retail'
		dataType: string
		lineageTag: d86ff6b6-b652-4ffe-b998-947a2cb5855a
		summarizeBy: none
		sourceColumn: Nombre del retail

		annotation SummarizationSetBy = Automatic

	column 'Código local'
		dataType: string
		lineageTag: 8cba446a-6eb8-440e-af7b-ac1abb9be378
		summarizeBy: none
		sourceColumn: Código local

		annotation SummarizationSetBy = Automatic

	column Activo
		dataType: string
		lineageTag: f098a72e-01a5-437a-9c1f-6de9d3a2311c
		summarizeBy: none
		sourceColumn: Activo

		annotation SummarizationSetBy = Automatic

	partition 'Pdv DiDi' = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\adrian.arriaga\OneDrive - Adecco\Documents\Adrian\Didi\Dashboard_Ventas_Cancelaciones\PDV DiDi.xlsx"), null, true),
				    PontoDeVendaExport_Sheet = Origen{[Item="PontoDeVendaExport",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(PontoDeVendaExport_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID", Int64.Type}, {"Nombre del PDV", type text}, {"Nombre de fantasía", type text}, {"Razón social", type text}, {"Cadena", type text}, {"Red", type text}, {"Tipo de PDV", type text}, {"Perfil del PDV", type text}, {"Canal del PDV", type text}, {"Núm. del PDV", type text}, {"Regional", type text}, {"Macrorregional", type text}, {"Código del PDV", type text}, {"Cantidad de cajas", type text}, {"Gerente", type text}, {"Cumpleaños del gerente", type text}, {"Núm. de Identificación Empresarial", type text}, {"Teléfono", type text}, {"FAX", type text}, {"Ciudad", type text}, {"División territorial", type text}, {"Dirección", type text}, {"Número", type text}, {"Complemento", type text}, {"Barrio", type text}, {"Código postal", type text}, {"Latitud", type text}, {"Longitud", type text}, {"Centro comercial", type text}, {"Facturación", type text}, {"Volumen", type text}, {"Nombre del retail", type text}, {"Código local", type text}, {"Activo", type text}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

