table Ventas
	lineageTag: 8867996b-cdc2-4984-9581-e4aedd4d582a

	column 'ID de la encuesta'
		dataType: int64
		formatString: 0
		lineageTag: 5d504751-83f9-4aa7-91d8-5a4020f3ac7c
		summarizeBy: sum
		sourceColumn: ID de la encuesta

		annotation SummarizationSetBy = Automatic

	column 'Rótulo de la encuesta'
		dataType: string
		lineageTag: e1cd0a93-a7b1-4c77-9f4f-cb111ebe5d6c
		summarizeBy: none
		sourceColumn: Rótulo de la encuesta

		annotation SummarizationSetBy = Automatic

	column Red
		dataType: string
		lineageTag: f9cb331a-c823-45cf-8ee8-5ff8e6991f4b
		summarizeBy: none
		sourceColumn: Red

		annotation SummarizationSetBy = Automatic

	column Cadena
		dataType: string
		lineageTag: ba52b5f3-7e86-42a2-a8a6-ad20b267af33
		summarizeBy: none
		sourceColumn: Cadena

		annotation SummarizationSetBy = Automatic

	column PDV
		dataType: string
		lineageTag: 732017bc-eb75-4595-8510-8d9d239e95a2
		summarizeBy: none
		sourceColumn: PDV

		annotation SummarizationSetBy = Automatic

	column 'División territorial'
		dataType: string
		lineageTag: fbbefb11-031a-41f3-be07-5459a5e5be77
		summarizeBy: none
		sourceColumn: División territorial

		annotation SummarizationSetBy = Automatic

	column Ciudad
		dataType: string
		lineageTag: 3964b085-26e2-40ce-a261-9ee2c9bad700
		summarizeBy: none
		sourceColumn: Ciudad

		annotation SummarizationSetBy = Automatic

	column Regional
		dataType: string
		lineageTag: 933f966f-4b98-433e-83fc-72c24af0ad08
		summarizeBy: none
		sourceColumn: Regional

		annotation SummarizationSetBy = Automatic

	column Empleado
		dataType: string
		lineageTag: d7afb91d-fd5c-4cbb-a96c-cf9bc0e596d9
		summarizeBy: none
		sourceColumn: Empleado

		annotation SummarizationSetBy = Automatic

	column 'ID Pedido'
		dataType: string
		lineageTag: a0aea62a-f65b-4323-8656-c3f2586233e5
		summarizeBy: none
		sourceColumn: ID Pedido

		annotation SummarizationSetBy = Automatic

	column 'Cantidad de articulos'
		dataType: int64
		formatString: 0
		lineageTag: fa659c22-c94b-4fc4-8e62-e1a1a0a5c6af
		summarizeBy: sum
		sourceColumn: Cantidad de articulos

		annotation SummarizationSetBy = Automatic

	column '¿A qué hora recibiste el pedido en la aplicación?'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 91989cb0-7e6c-4af8-a873-a4687a0b854d
		summarizeBy: none
		sourceColumn: ¿A qué hora recibiste el pedido en la aplicación?

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column '¿A qué hora fue registrado el pago?'
		dataType: dateTime
		formatString: Long Time
		lineageTag: 4109c787-8c55-4f13-ae92-fa2dbb350133
		summarizeBy: none
		sourceColumn: ¿A qué hora fue registrado el pago?

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Mes = FORMAT(Ventas[Fecha y hora de la encuesta],"MMMM")
		lineageTag: 84a14a17-aaee-4a78-a56d-c52c8aad8f7e
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column Dia = DAY(Ventas[Fecha y hora de la encuesta])
		formatString: 0
		lineageTag: 7f014f03-5f76-4125-9ac8-33e69f4a5c22
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Fecha y hora de la encuesta'
		dataType: dateTime
		formatString: General Date
		lineageTag: 5360cc6d-33be-40bf-b5db-dcc905d06761
		summarizeBy: none
		sourceColumn: Fecha y hora de la encuesta

		annotation SummarizationSetBy = Automatic

	column 'Cantidad total de la Factura'
		dataType: int64
		formatString: 0
		lineageTag: d300f2a3-8627-4cc8-b093-5a6da8b913c9
		summarizeBy: sum
		sourceColumn: Cantidad total de la Factura

		annotation SummarizationSetBy = Automatic

	column '¿Se solicito vehículo para la orden?'
		dataType: string
		lineageTag: 4d16dd11-538b-49f6-aed7-5be749054876
		summarizeBy: none
		sourceColumn: ¿Se solicito vehículo para la orden?

		annotation SummarizationSetBy = Automatic

	column 'Tipo de vehiculo'
		dataType: string
		lineageTag: 6e44a5a1-1bd3-4085-aeb7-8b79849b3c56
		summarizeBy: none
		sourceColumn: Tipo de vehiculo

		annotation SummarizationSetBy = Automatic

	column 'Costo del vehiculo'
		dataType: string
		lineageTag: b10a4507-a75b-42c1-9530-7db153c50ccc
		summarizeBy: none
		sourceColumn: Costo del vehiculo

		annotation SummarizationSetBy = Automatic

	partition Ventas = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\adrian.arriaga\OneDrive - Adecco\Documents\Adrian\Didi\Dashboard_Ventas_Cancelaciones\VENTAS.xlsx"), null, true),
				    report_Sheet = Origen{[Item="report",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos1" = Table.PromoteHeaders(report_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Encabezados promovidos1",{{"ID de la encuesta", Int64.Type}, {"Rótulo de la encuesta", type text}, {"Red", type text}, {"Cadena", type text}, {"PDV", type text}, {"División territorial", type text}, {"Ciudad", type text}, {"Regional", type text}, {"Fecha y hora de la encuesta", type datetime}, {"Empleado", type text}, {"ID Pedido", type text}, {"Cantidad de articulos", Int64.Type}, {"¿A qué hora recibiste el pedido en la aplicación?", type time}, {"¿A qué hora fue registrado el pago?", type time}, {"Cantidad total de la Factura", Int64.Type}})
				in
				    #"Tipo cambiado1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

